import { centralModules, reportsModules } from '@/lib/permissionModules';

export const permissionSystems = [
  {
    key: 'central',
    label: 'Central',
    description: 'Gestao de estoque/TI, ativos, colaboradores e operacao administrativa.',
    status: 'active',
    route: '/',
    devPort: 5173,
    modules: centralModules,
  },
  {
    key: 'relatorios',
    label: 'Relatorios',
    description: 'Paineis, analises e permissoes especificas de relatorios.',
    status: 'active',
    route: '/',
    devPort: 5174,
    modules: reportsModules,
  },
  {
    key: 'intranet',
    label: 'Intranet',
    description: 'Comunicacao interna, conteudos corporativos e comunicados.',
    status: 'planned',
    route: '/',
    devPort: 5175,
    modules: [],
  },
  {
    key: 'pagamentos',
    label: 'Pagamentos',
    description: 'Solicitacoes e fluxo de aprovacao de pagamentos.',
    status: 'active',
    route: '/',
    devPort: 5177,
    modules: [],
  },
  {
    key: 'crm',
    label: 'CRM',
    description: 'Relacionamento comercial, leads e acompanhamento de oportunidades.',
    status: 'active',
    route: '/',
    devPort: 5172,
    modules: [
      { key: 'leads', label: 'Leads' },
      { key: 'clientes', label: 'Clientes' },
      { key: 'atividades', label: 'Atividades' },
    ],
  },
  {
    key: 'rh',
    label: 'RH',
    description: 'Estrutura reservada para processos e rotinas de recursos humanos.',
    status: 'planned',
    route: '/',
    devPort: null,
    modules: [],
  },
];
